inputs:
  ssh-private-key:  # id of input
    # PRB: vlipovetskii/gha-ssh-agent/main/action.yml (Line: 5, Col: 18): Unrecognized named-value: 'vars'. Located at position 1 within expression: vars.SSH_AUTH_SOCK
    # WO:  \$ ...
    description: 'SSH private key: as a rule secrets.SSH_PRIVATE_KEY'
    required: true
    # default: '???'
runs:
  using: "composite"
  steps:
    - name: Setup SSH key
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ inputs.ssh-private-key }}"
      shell: bash
